ENV_VAR__WCF_SERVICE__AUTH__API_KEY__NAME              = "WCF_SERVICE__AUTH__API_KEY__NAME"
ENV_VAR__WCF_SERVICE__AUTH__API_KEY__VALUE             = "WCF_SERVICE__AUTH__API_KEY__VALUE"
ENV_VAR__AUTH__TARGET_SERVER__CACHE_SERVICE__BASE_URL  = "AUTH__TARGET_SERVER__CACHE_SERVICE__BASE_URL"
ENV_VAR__AUTH__TARGET_SERVER__CACHE_SERVICE__KEY_NAME  = "AUTH__TARGET_SERVER__CACHE_SERVICE__KEY_NAME"
ENV_VAT__AUTH__TARGET_SERVER__CACHE_SERVICE__KEY_VALUE = "AUTH__TARGET_SERVER__CACHE_SERVICE__KEY_VALUE"


DEFAULT__WCF__PROXY__TIMEOUT = 5.0                                          # max five seconds